import type { CartItem, Scenario, Substitute } from "./types";

// ─── Product emoji icons (used as img placeholder) ───────────────
const IMG = {
  tea:      "🫖",
  milk:     "🥛",
  sugar:    "🍬",
  snacks:   "🍪",
  cups:     "🥤",
  napkins:  "🧻",
  plates:   "🍽️",
  water:    "💧",
  juice:    "🧃",
  coffee:   "☕",
  bread:    "🍞",
  butter:   "🧈",
  eggs:     "🥚",
  paracetamol:"💊",
  crocin:   "💊",
  vaporub:  "🫙",
  tissues:  "🤧",
  ors:      "🧂",
  soup:     "🍲",
  fruits:   "🍊",
  honey:    "🍯",
  umbrella: "☂️",
  raincoat: "🧥",
  boots:    "👢",
  candle:   "🕯️",
  torch:    "🔦",
  battery:  "🔋",
  powerbank:"🔋",
  match:    "🔥",
  agarbatti:"🪔",
  flowers:  "🌸",
  coconut:  "🥥",
  pooja:    "🪔",
  camphor:  "🕯️",
  rice:     "🍚",
  dal:      "🫘",
  pen:      "✏️",
  notebook: "📓",
  glue:     "🔧",
  scissors: "✂️",
  color:    "🎨",
  luggage:  "🧳",
  sanitizer:"🧴",
  charger:  "🔌",
  snackbox: "📦",
};

function sub(
  id: string,
  name: string,
  brand: string,
  price: number,
  type: Substitute["type"],
  label: string,
  reason: string,
  eta: number,
  icon: string
): Substitute {
  return { id, name, brand, price, type, label, reason, eta, image: icon };
}

function item(
  id: string,
  name: string,
  brand: string,
  category: string,
  price: number,
  qty: number,
  unit: string,
  icon: string,
  reason: string,
  reasonTag: string,
  eta: number,
  substitutes: Substitute[],
  isEssential = true,
  isAddon = false
): CartItem {
  return {
    id, name, brand, category, price, quantity: qty, unit,
    image: icon, reason, reasonTag, eta, substitutes, isEssential, isAddon,
  };
}

// ─── Scenario → Cart map ──────────────────────────────────────────
export const SCENARIO_CARTS: Record<Scenario, CartItem[]> = {

  hosting: [
    item("h1","Tea Powder","Tata Tea",     "Beverages",  89, 1,"500g", IMG.tea,
      "Core hosting essential for serving guests","Hosting essential", 12,
      [sub("h1a","Brooke Bond","HUL",79,"fastest","Fastest","Available at nearest dark store",8,IMG.tea),
       sub("h1b","Society Tea","Society",65,"cheapest","Best Value","₹24 cheaper",12,IMG.tea),
       sub("h1c","Darjeeling Blend","Wagh Bakri",110,"trusted","Most Trusted","Premium quality for guests",14,IMG.tea)]),
    item("h2","Full Cream Milk","Amul",    "Dairy",      60, 2,"1L",   IMG.milk,
      "Required to prepare tea for multiple guests","Required for serving", 12,
      [sub("h2a","Mother Dairy Milk","Mother Dairy",58,"fastest","Fastest","8 min ETA",8,IMG.milk),
       sub("h2b","Nandini Milk","KMF",54,"cheapest","Best Value","₹6 cheaper per litre",10,IMG.milk)]),
    item("h3","Sugar","Madhur",            "Staples",    45, 1,"1kg",  IMG.sugar,
      "Sweetener for tea and beverages","Serving necessity", 12,
      [sub("h3a","Raw Sugar","Natural",55,"trusted","Most Trusted","Healthier option",13,IMG.sugar)]),
    item("h4","Marie Gold Biscuits","Britannia","Snacks",35, 2,"200g", IMG.snacks,
      "Classic accompaniment for tea service","Tea pairing", 12,
      [sub("h4a","Good Day","Britannia",40,"trusted","Most Trusted","Premium biscuit option",12,IMG.snacks),
       sub("h4b","Parle-G","Parle",20,"cheapest","Best Value","₹15 cheaper, crowd favourite",8,IMG.snacks)]),
    item("h5","Paper Cups","Chuk",         "Disposables",49, 1,"50pcs",IMG.cups,
      "Quick serving solution for multiple guests","Quick serving", 12,
      [sub("h5a","Solo Cups","Solo",55,"trusted","Most Trusted","Leak-proof quality",14,IMG.cups)]),
    item("h6","Napkins","Tork",            "Disposables",39, 1,"100pcs",IMG.napkins,
      "Cleanup convenience for guests","Cleanup convenience", 12, []),
    item("h7","Khari Biscuits","Parle",    "Snacks",     30, 1,"250g", IMG.snacks,
      "Savoury option for varied guest preferences","Savory option", 14, [], false, true),
  ],

  fever: [
    item("f1","Paracetamol 500mg","Dolo","Medicines",  52, 2,"strip",IMG.paracetamol,
      "Primary fever and pain relief medication","Fever relief", 10,
      [sub("f1a","Calpol 500","GSK",45,"fastest","Fastest","Available now",8,IMG.paracetamol),
       sub("f1b","Crocin Advance","GSK",60,"trusted","Most Trusted","Doctor recommended brand",10,IMG.paracetamol)]),
    item("f2","Vicks VapoRub","Vicks",     "Medicines",  89, 1,"25g",  IMG.vaporub,
      "Chest rub for cold and congestion relief","Congestion relief", 10, []),
    item("f3","Soft Tissues","Kleenex",    "Health",     49, 2,"100pcs",IMG.tissues,
      "Hygienic option for frequent nose blowing","Hygiene essential", 10,
      [sub("f3a","Puffs","P&G",55,"trusted","Most Trusted","Softer on skin",12,IMG.tissues)]),
    item("f4","ORS Sachets","Electral",    "Medicines",  45, 5,"sachet",IMG.ors,
      "Electrolyte replacement to prevent dehydration","Hydration", 10, []),
    item("f5","Chicken Soup","Knorr",      "Food",       65, 2,"pkt",  IMG.soup,
      "Comforting warm meal during illness","Recovery nutrition", 12,
      [sub("f5a","Ching's Soup","Capital",45,"cheapest","Best Value","₹20 cheaper",10,IMG.soup)]),
    item("f6","Honey","Dabur",             "Health",     120,1,"250g", IMG.honey,
      "Natural sore throat remedy","Natural remedy", 12, [], false, true),
    item("f7","Lemon","Fresh",             "Produce",    20, 4,"pcs",  IMG.fruits,
      "Vitamin C boost and natural immunity support","Immunity boost", 15, [], false, true),
  ],

  pooja: [
    item("p1","Agarbatti","Cycle",         "Pooja",      35, 2,"pack", IMG.agarbatti,
      "Essential incense for pooja ceremony","Pooja essential", 14,
      [sub("p1a","HEM Agarbatti","HEM",29,"cheapest","Best Value","₹6 cheaper",14,IMG.agarbatti),
       sub("p1b","Moksh Agarbatti","Moksh",55,"trusted","Most Trusted","Premium fragrance",16,IMG.agarbatti)]),
    item("p2","Camphor","Mangaldeep",      "Pooja",      25, 1,"box",  IMG.camphor,
      "Required for aarti ritual","Aarti ritual", 14, []),
    item("p3","Pooja Flowers","Fresh",     "Pooja",      80, 1,"bunch",IMG.flowers,
      "Fresh marigold and rose offerings for deity","Deity offering", 20,
      [sub("p3a","Artificial Flowers","Craft",60,"fastest","Fastest","Always in stock",14,IMG.flowers)]),
    item("p4","Coconut","Fresh",           "Produce",    30, 2,"pcs",  IMG.coconut,
      "Auspicious offering for pooja ritual","Sacred offering", 18, []),
    item("p5","Ghee","Amul",              "Dairy",      180,1,"500g", IMG.butter,
      "Pure ghee for diyas and prasad preparation","Diya fuel & prasad", 14,
      [sub("p5a","Patanjali Ghee","Patanjali",160,"cheapest","Best Value","₹20 cheaper",16,IMG.butter)]),
    item("p6","Rice","India Gate",         "Staples",    60, 1,"1kg",  IMG.rice,
      "Akshat (raw rice) for ritual offering","Ritual offering", 14, []),
    item("p7","Turmeric","Everest",        "Spices",     35, 1,"100g", IMG.pooja,
      "Haldi for tilak and purification ritual","Purification ritual", 14, [], false, true),
  ],

  rainy: [
    item("r1","Hot Chocolate","Cadbury",   "Beverages",  130,1,"200g", IMG.coffee,
      "Perfect warm drink for a rainy day indoors","Rainy day comfort", 14,
      [sub("r1a","Bru Cappuccino","HUL",90,"cheapest","Best Value","₹40 cheaper",14,IMG.coffee),
       sub("r1b","Starbucks Via","Starbucks",220,"trusted","Most Trusted","Premium cafe quality",16,IMG.coffee)]),
    item("r2","Bread","Britannia",         "Bakery",     38, 1,"400g", IMG.bread,
      "Staple for indoor cooking on a rainy day","Indoor meal", 12,
      [sub("r2a","Modern Bread","Modern",35,"cheapest","Best Value","₹3 cheaper",10,IMG.bread)]),
    item("r3","Butter","Amul",             "Dairy",      55, 1,"100g", IMG.butter,
      "Pairs with bread for a quick warm snack","Snack pairing", 12, []),
    item("r4","Eggs","Nandini",            "Protein",    75, 6,"pcs",  IMG.eggs,
      "Quick protein-rich meal option","Rainy day meal", 15,
      [sub("r4a","Farm Fresh Eggs","Local",65,"cheapest","Best Value","₹10 cheaper",12,IMG.eggs)]),
    item("r5","Maggi Noodles","Nestle",    "Snacks",     14, 4,"pkt",  IMG.snacks,
      "Classic comfort food for rainy evenings","Comfort food", 12,
      [sub("r5a","Yippee Noodles","ITC",12,"cheapest","Best Value","₹2 cheaper",10,IMG.snacks)]),
    item("r6","Candles","Fevi",            "Emergency",  49, 2,"pack", IMG.candle,
      "Backup lighting in case of power outage","Power backup", 18, []),
  ],

  travel: [
    item("t1","Water Bottle","Bisleri",    "Hydration",  20, 2,"1L",   IMG.water,
      "Essential hydration for journey","Travel essential", 10,
      [sub("t1a","Kinley","Coca-Cola",18,"fastest","Fastest","8 min ETA",8,IMG.water),
       sub("t1b","Evian","Evian",45,"trusted","Most Trusted","Premium mineral water",14,IMG.water)]),
    item("t2","Trail Mix","Too Yumm",      "Snacks",     60, 2,"60g",  IMG.snackbox,
      "Healthy travel snack to avoid airport prices","Travel snack", 12, []),
    item("t3","Energy Bar","Yoga Bar",     "Health",     55, 3,"38g",  IMG.snacks,
      "Quick energy boost during long journeys","Energy boost", 12,
      [sub("t3a","Snickers","Mars",45,"cheapest","Best Value","₹10 cheaper",10,IMG.snacks)]),
    item("t4","Hand Sanitizer","Dettol",   "Hygiene",    75, 1,"100ml",IMG.sanitizer,
      "Hygiene essential for travel","Travel hygiene", 12, []),
    item("t5","Travel Charger","Syska",    "Electronics",299,1,"pcs",  IMG.charger,
      "Keep devices charged during transit","Device power", 20,
      [sub("t5a","Ambrane Charger","Ambrane",249,"cheapest","Best Value","₹50 cheaper",18,IMG.charger)]),
    item("t6","Notebook","Classmate",      "Stationery", 35, 1,"pcs",  IMG.notebook,
      "Jot notes or entertain during travel","Travel companion", 14, [], false, true),
  ],

  power_cut: [
    item("pc1","LED Torch","Eveready",     "Emergency",  199,1,"pcs",  IMG.torch,
      "Immediate lighting during power outage","Emergency light", 14,
      [sub("pc1a","Philips Torch","Philips",249,"trusted","Most Trusted","Brighter beam",14,IMG.torch),
       sub("pc1b","Local Torch","Generic",149,"cheapest","Best Value","₹50 cheaper",12,IMG.torch)]),
    item("pc2","AA Batteries","Duracell",  "Emergency",  120,1,"4pcs", IMG.battery,
      "Power source for torches and devices","Battery backup", 14,
      [sub("pc2a","Energizer","Energizer",110,"trusted","Most Trusted","Longer life",14,IMG.battery),
       sub("pc2b","Eveready","Eveready",80,"cheapest","Best Value","₹40 cheaper",12,IMG.battery)]),
    item("pc3","Candles","Paraffin",       "Emergency",  49, 3,"pack", IMG.candle,
      "Ambient backup lighting for extended outages","Ambient light", 12, []),
    item("pc4","Matchbox","Vivek",         "Emergency",  15, 2,"pcs",  IMG.match,
      "Fire starter for candles and emergency use","Fire starter", 12, []),
    item("pc5","Power Bank 20000mAh","MI", "Electronics",999,1,"pcs",  IMG.powerbank,
      "Keep mobile charged during extended outage","Phone backup", 18,
      [sub("pc5a","Ambrane 20000","Ambrane",799,"cheapest","Best Value","₹200 cheaper",16,IMG.powerbank),
       sub("pc5b","Anker 20000","Anker",1199,"trusted","Most Trusted","Premium build quality",20,IMG.powerbank)]),
    item("pc6","Water (Stored)","Bisleri", "Emergency",  60, 2,"2L",   IMG.water,
      "Stock water in case pump fails","Water backup", 12, []),
  ],

  school: [
    item("sc1","HB Pencils","Camlin",      "Stationery", 30, 1,"10pcs",IMG.pen,
      "Standard requirement for school project work","Project essential", 12,
      [sub("sc1a","Natraj Pencil","Hindustan",20,"cheapest","Best Value","₹10 cheaper",10,IMG.pen)]),
    item("sc2","A4 Notebook","Classmate",  "Stationery", 45, 2,"pcs",  IMG.notebook,
      "Drawing and writing pages for project","Project base", 12, []),
    item("sc3","Colour Pencils","Camlin",  "Stationery", 85, 1,"12pcs",IMG.color,
      "Colouring and illustration for project","Illustration", 12,
      [sub("sc3a","Apsara Colour","Hindustan",70,"cheapest","Best Value","₹15 cheaper",12,IMG.color)]),
    item("sc4","Fevicol","Pidilite",       "Stationery", 25, 1,"75g",  IMG.glue,
      "Adhesive for cutting and pasting project work","Project adhesive", 12, []),
    item("sc5","Scissors","Classmate",     "Stationery", 45, 1,"pcs",  IMG.scissors,
      "Cutting tool for craft and project work","Craft tool", 14, []),
    item("sc6","Drawing Sheets","ITC",     "Stationery", 20, 5,"pcs",  IMG.notebook,
      "Extra display sheets for project presentation","Display sheets", 12, []),
    item("sc7","Ruler","Camlin",           "Stationery", 15, 1,"30cm", IMG.pen,
      "Measurement and straight line tool","Measurement tool", 12, [], false, true),
  ],

  tea_break: [
    item("tb1","Tea Bags","Lipton",        "Beverages",  99, 1,"25bag",IMG.tea,
      "Quick-brew tea without boiling milk","Quick tea", 10,
      [sub("tb1a","Tata Tea Bags","Tata",85,"fastest","Fastest","8 min ETA",8,IMG.tea),
       sub("tb1b","Tetley Bags","Tetley",110,"trusted","Most Trusted","Smooth flavour",12,IMG.tea)]),
    item("tb2","Milk","Amul",              "Dairy",      30, 1,"500ml",IMG.milk,
      "Required for milk-based tea preparation","Tea essential", 10, []),
    item("tb3","Sugar","Madhur",           "Staples",    30, 1,"500g", IMG.sugar,
      "Sweetener for tea","Tea sweetener", 10, []),
    item("tb4","Parle-G","Parle",          "Snacks",     10, 2,"100g", IMG.snacks,
      "Classic biscuit for tea time dunking","Tea companion", 10,
      [sub("tb4a","Monaco","Parle",20,"trusted","Most Trusted","Premium cracker option",10,IMG.snacks)]),
    item("tb5","Namkeen Mix","Haldirams",  "Snacks",     50, 1,"150g", IMG.snacks,
      "Savoury snack for tea break","Savoury option", 12,
      [sub("tb5a","Bikaji Bhujia","Bikaji",45,"cheapest","Best Value","₹5 cheaper",12,IMG.snacks)]),
  ],

  general: [
    item("g1","Mineral Water","Bisleri",   "Hydration",  20, 2,"1L",   IMG.water,
      "Basic hydration essential","Essential", 10, []),
    item("g2","Bread","Britannia",         "Bakery",     38, 1,"400g", IMG.bread,
      "Everyday meal staple","Meal staple", 12, []),
    item("g3","Milk","Amul",               "Dairy",      30, 1,"500ml",IMG.milk,
      "Daily dairy requirement","Daily essential", 12, []),
    item("g4","Eggs","Nandini",            "Protein",    75, 6,"pcs",  IMG.eggs,
      "Quick protein source","Protein source", 14, []),
    item("g5","Instant Noodles","Maggi",   "Snacks",     14, 2,"pkt",  IMG.snacks,
      "Quick meal option","Quick meal", 10, []),
  ],
};
